package gov.naco.soch.enums;

public enum NotificationEventId {

	ADD_USER("1"), DELETE_USER("2"), ADD_DIVISION("3"), DELETE_DIVISION("4"), ADD_ROLE("5"), DELETE_ROLE("6"),
	ADD_DESIGNATION("7"), DELETE_DESIGNATION("8"), ADD_FACILITY("9"), DELETE_FACILITY("10"), ADD_BENEFICIARY_CST("11"),
	DELETE_BENEFICIARY_CST("12"), ADD_LAC_CST("13"), DELETE_LAC_CST("14"), BENEFICIARY_REFERRAL_CST("15"),
	SEND_REGISTRATION_DETAILS_TO_USER("16"), ADD_SACS("17"), ADD_LABS("18"), ADD_SUPPLIER("19"), ADD_RWH("20"),
	ADD_SACS_FACILITY("21"),RESET_PASSWORD("22"),APPROVE_CONTRACT("23"),DISCONTINUE_NOA("24"),DISPATCH_BY_SUPPLIER("25"),
	GENERATE_GRN_1("26"),GENERATE_GRN_2("27"),SACS_RECEIPT_UNREGISTERED("28"),RECEIPT_FROM_SACS("29"),SACS_INVENTORY_CONTROL("30"),
	SAVE_RECEIPT_DETAILS("31"),DISPATCH_TO_UNREGISTERED_FACILITY("32"),FACILITY_RECEIPT_UNREGISTERED("33"),FACILITY_GENERATE_GRN1("34"),
	FACILITY_RECEIPT_FROM_WAREHOUSE("35"),SACS_RECEIPT_FROM_SUPPLIER("36"),SACS_DISPATCH_TO_FACILITY("37"),SACS_DISPATCH_TO_OTHER_FACILITY("38"),
	STN_GENERATED_FACILITY_RELOCATION_TO_FACILITY("39"),STN_GENERATED_FACILITY_RELOCATION_TO_SACS("40"),FACILITY_INVENTORY_CONTROL("41"),
	DISPATCH_APPROVAL("42"),DISPATCH_APPROVED("43"),ADD_PRODUCT("44"),REMIND_EXPIRY_DATE("45"),OTP_GENERATED("46"),CHANGE_PASSWORD_FOR_USER("47"), ICTC_ART_REFERRAL("49");

	private String eventId;

	NotificationEventId(String eventId) {
		this.eventId = eventId;
	}

	public String getEventId() {
		return this.eventId;
	}

}

