package gov.naco.soch.domain;

import java.time.LocalDateTime;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(FICTCMonthlyReportEntity.class)
public abstract class FICTCMonthlyReportEntity_ {

	public static volatile SingularAttribute<FICTCMonthlyReportEntity, LocalDateTime> modifiedTime;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> testedForSyphillisFemale;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> obgGynOutreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> ancClientsReactive;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> rnctpInreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> tHivFemaleClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> tiNgosOutreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivConsumedQuantity;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivQuantityIndent;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> tHivAncCount;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> testedForSyphillisMale;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> potcFemaleClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivReceivedQuantity;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> tHivDirectInLabour;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, LocalDateTime> createdTime;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> tHivTgClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> bloodOpeningStock;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Long> id;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> otherOutreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> diagnosedStiRtiFemale;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> sticClinicInreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> prtcMaleClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> ancClientsRegistered;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> prtcTgClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, String> bloodBatchNumber;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> diagnosedStiRtiMale;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> rnctpOutreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> potcAncCount;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivReactiveDirectInLabour;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Boolean> reportSubmitStatus;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> reactiveForSyphillisFemale;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, String> hivBatchNumber;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> reportYear;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> linkWorkerInreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> bloodQuantityIndent;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> tiNgosInreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivReactiveFemaleClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, String> bloodKitName;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Boolean> availabilityDrugType;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> tHivMaleClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> potcMaleClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, LocalDateTime> bloodExpiryDate;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivOpeningStock;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivReactiveAncCount;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> sticClinicOutreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> potcDirectInLabour;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivWastageQuantity;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, LocalDateTime> hivExpiryDate;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivControlQuantity;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> prtcAncCount;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> prtcDirectInLabour;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Long> modifiedBy;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> obgGynInreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> otherInreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> bloodWastageQuantity;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> reportMonth;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> facilityId;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> prtcFemaleClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivReactiveTgClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> hivReactiveMaleClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> ancClientsTested;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> linkWorkerOutreferral;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> potcTgClients;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, String> hivKitName;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> reactiveForSyphillisMale;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Long> createdBy;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> bloodReceivedQuantity;
	public static volatile SingularAttribute<FICTCMonthlyReportEntity, Integer> bloodConsumedQuantity;

	public static final String MODIFIED_TIME = "modifiedTime";
	public static final String TESTED_FOR_SYPHILLIS_FEMALE = "testedForSyphillisFemale";
	public static final String OBG_GYN_OUTREFERRAL = "obgGynOutreferral";
	public static final String ANC_CLIENTS_REACTIVE = "ancClientsReactive";
	public static final String RNCTP_INREFERRAL = "rnctpInreferral";
	public static final String T_HIV_FEMALE_CLIENTS = "tHivFemaleClients";
	public static final String TI_NGOS_OUTREFERRAL = "tiNgosOutreferral";
	public static final String HIV_CONSUMED_QUANTITY = "hivConsumedQuantity";
	public static final String HIV_QUANTITY_INDENT = "hivQuantityIndent";
	public static final String T_HIV_ANC_COUNT = "tHivAncCount";
	public static final String TESTED_FOR_SYPHILLIS_MALE = "testedForSyphillisMale";
	public static final String POTC_FEMALE_CLIENTS = "potcFemaleClients";
	public static final String HIV_RECEIVED_QUANTITY = "hivReceivedQuantity";
	public static final String T_HIV_DIRECT_IN_LABOUR = "tHivDirectInLabour";
	public static final String CREATED_TIME = "createdTime";
	public static final String T_HIV_TG_CLIENTS = "tHivTgClients";
	public static final String BLOOD_OPENING_STOCK = "bloodOpeningStock";
	public static final String ID = "id";
	public static final String OTHER_OUTREFERRAL = "otherOutreferral";
	public static final String DIAGNOSED_STI_RTI_FEMALE = "diagnosedStiRtiFemale";
	public static final String STIC_CLINIC_INREFERRAL = "sticClinicInreferral";
	public static final String PRTC_MALE_CLIENTS = "prtcMaleClients";
	public static final String ANC_CLIENTS_REGISTERED = "ancClientsRegistered";
	public static final String PRTC_TG_CLIENTS = "prtcTgClients";
	public static final String BLOOD_BATCH_NUMBER = "bloodBatchNumber";
	public static final String DIAGNOSED_STI_RTI_MALE = "diagnosedStiRtiMale";
	public static final String RNCTP_OUTREFERRAL = "rnctpOutreferral";
	public static final String POTC_ANC_COUNT = "potcAncCount";
	public static final String HIV_REACTIVE_DIRECT_IN_LABOUR = "hivReactiveDirectInLabour";
	public static final String REPORT_SUBMIT_STATUS = "reportSubmitStatus";
	public static final String REACTIVE_FOR_SYPHILLIS_FEMALE = "reactiveForSyphillisFemale";
	public static final String HIV_BATCH_NUMBER = "hivBatchNumber";
	public static final String REPORT_YEAR = "reportYear";
	public static final String LINK_WORKER_INREFERRAL = "linkWorkerInreferral";
	public static final String BLOOD_QUANTITY_INDENT = "bloodQuantityIndent";
	public static final String TI_NGOS_INREFERRAL = "tiNgosInreferral";
	public static final String HIV_REACTIVE_FEMALE_CLIENTS = "hivReactiveFemaleClients";
	public static final String BLOOD_KIT_NAME = "bloodKitName";
	public static final String AVAILABILITY_DRUG_TYPE = "availabilityDrugType";
	public static final String T_HIV_MALE_CLIENTS = "tHivMaleClients";
	public static final String POTC_MALE_CLIENTS = "potcMaleClients";
	public static final String BLOOD_EXPIRY_DATE = "bloodExpiryDate";
	public static final String HIV_OPENING_STOCK = "hivOpeningStock";
	public static final String HIV_REACTIVE_ANC_COUNT = "hivReactiveAncCount";
	public static final String STIC_CLINIC_OUTREFERRAL = "sticClinicOutreferral";
	public static final String POTC_DIRECT_IN_LABOUR = "potcDirectInLabour";
	public static final String HIV_WASTAGE_QUANTITY = "hivWastageQuantity";
	public static final String HIV_EXPIRY_DATE = "hivExpiryDate";
	public static final String HIV_CONTROL_QUANTITY = "hivControlQuantity";
	public static final String PRTC_ANC_COUNT = "prtcAncCount";
	public static final String PRTC_DIRECT_IN_LABOUR = "prtcDirectInLabour";
	public static final String MODIFIED_BY = "modifiedBy";
	public static final String OBG_GYN_INREFERRAL = "obgGynInreferral";
	public static final String OTHER_INREFERRAL = "otherInreferral";
	public static final String BLOOD_WASTAGE_QUANTITY = "bloodWastageQuantity";
	public static final String REPORT_MONTH = "reportMonth";
	public static final String FACILITY_ID = "facilityId";
	public static final String PRTC_FEMALE_CLIENTS = "prtcFemaleClients";
	public static final String HIV_REACTIVE_TG_CLIENTS = "hivReactiveTgClients";
	public static final String HIV_REACTIVE_MALE_CLIENTS = "hivReactiveMaleClients";
	public static final String ANC_CLIENTS_TESTED = "ancClientsTested";
	public static final String LINK_WORKER_OUTREFERRAL = "linkWorkerOutreferral";
	public static final String POTC_TG_CLIENTS = "potcTgClients";
	public static final String HIV_KIT_NAME = "hivKitName";
	public static final String REACTIVE_FOR_SYPHILLIS_MALE = "reactiveForSyphillisMale";
	public static final String CREATED_BY = "createdBy";
	public static final String BLOOD_RECEIVED_QUANTITY = "bloodReceivedQuantity";
	public static final String BLOOD_CONSUMED_QUANTITY = "bloodConsumedQuantity";

}

