package gov.naco.soch.domain;

import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(ICTCBeneficiaryVisit.class)
public abstract class ICTCBeneficiaryVisit_ {

	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> beneficiaryStatus;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> beneficiaryStatusDesc;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> mobileNumber;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> labName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> pid;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, LocalDate> reportReceivedDate;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Boolean> isActive;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> hivStatusDesc;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> deletedReason;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> infantMotherBeneficiaryId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> visitId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> occupationId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> infantMotherFirstName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> labId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> infantBreastFed;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, LocalDate> visitDate;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> id;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> hivStatus;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> barcode;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> dsrcReferralName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> testTypeDesc;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> currentTestResultId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> dsrcReferralId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, LocalDateTime> sampleCollectionDate;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> artReferralId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> rntcpReferralId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> rntcpReferralName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> deletedReasonComment;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> firstName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> tiReferralId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> maritalStatusId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> hivType;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> labCode;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> beneficiaryId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> infantCode;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> lastName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> infantMotherLastName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, LocalDateTime> testedDate;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Boolean> isConsentDocumented;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> consignmentId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> testType;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> batchId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, LocalDateTime> resultModifiedTime;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> uid;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Boolean> isDeleted;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> tiReferralName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> artReferralName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> infantMotherArtNo;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Boolean> isPregnant;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> facilityId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> genderId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, LocalDate> dateOfBirth;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, LocalDate> reportDeliveryDate;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> registeredFacilityId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> resultStatus;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Long> infantMotherArtId;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> middleName;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, String> age;
	public static volatile SingularAttribute<ICTCBeneficiaryVisit, Integer> categoryId;

	public static final String BENEFICIARY_STATUS = "beneficiaryStatus";
	public static final String BENEFICIARY_STATUS_DESC = "beneficiaryStatusDesc";
	public static final String MOBILE_NUMBER = "mobileNumber";
	public static final String LAB_NAME = "labName";
	public static final String PID = "pid";
	public static final String REPORT_RECEIVED_DATE = "reportReceivedDate";
	public static final String IS_ACTIVE = "isActive";
	public static final String HIV_STATUS_DESC = "hivStatusDesc";
	public static final String DELETED_REASON = "deletedReason";
	public static final String INFANT_MOTHER_BENEFICIARY_ID = "infantMotherBeneficiaryId";
	public static final String VISIT_ID = "visitId";
	public static final String OCCUPATION_ID = "occupationId";
	public static final String INFANT_MOTHER_FIRST_NAME = "infantMotherFirstName";
	public static final String LAB_ID = "labId";
	public static final String INFANT_BREAST_FED = "infantBreastFed";
	public static final String VISIT_DATE = "visitDate";
	public static final String ID = "id";
	public static final String HIV_STATUS = "hivStatus";
	public static final String BARCODE = "barcode";
	public static final String DSRC_REFERRAL_NAME = "dsrcReferralName";
	public static final String TEST_TYPE_DESC = "testTypeDesc";
	public static final String CURRENT_TEST_RESULT_ID = "currentTestResultId";
	public static final String DSRC_REFERRAL_ID = "dsrcReferralId";
	public static final String SAMPLE_COLLECTION_DATE = "sampleCollectionDate";
	public static final String ART_REFERRAL_ID = "artReferralId";
	public static final String RNTCP_REFERRAL_ID = "rntcpReferralId";
	public static final String RNTCP_REFERRAL_NAME = "rntcpReferralName";
	public static final String DELETED_REASON_COMMENT = "deletedReasonComment";
	public static final String FIRST_NAME = "firstName";
	public static final String TI_REFERRAL_ID = "tiReferralId";
	public static final String MARITAL_STATUS_ID = "maritalStatusId";
	public static final String HIV_TYPE = "hivType";
	public static final String LAB_CODE = "labCode";
	public static final String BENEFICIARY_ID = "beneficiaryId";
	public static final String INFANT_CODE = "infantCode";
	public static final String LAST_NAME = "lastName";
	public static final String INFANT_MOTHER_LAST_NAME = "infantMotherLastName";
	public static final String TESTED_DATE = "testedDate";
	public static final String IS_CONSENT_DOCUMENTED = "isConsentDocumented";
	public static final String CONSIGNMENT_ID = "consignmentId";
	public static final String TEST_TYPE = "testType";
	public static final String BATCH_ID = "batchId";
	public static final String RESULT_MODIFIED_TIME = "resultModifiedTime";
	public static final String UID = "uid";
	public static final String IS_DELETED = "isDeleted";
	public static final String TI_REFERRAL_NAME = "tiReferralName";
	public static final String ART_REFERRAL_NAME = "artReferralName";
	public static final String INFANT_MOTHER_ART_NO = "infantMotherArtNo";
	public static final String IS_PREGNANT = "isPregnant";
	public static final String FACILITY_ID = "facilityId";
	public static final String GENDER_ID = "genderId";
	public static final String DATE_OF_BIRTH = "dateOfBirth";
	public static final String REPORT_DELIVERY_DATE = "reportDeliveryDate";
	public static final String REGISTERED_FACILITY_ID = "registeredFacilityId";
	public static final String RESULT_STATUS = "resultStatus";
	public static final String INFANT_MOTHER_ART_ID = "infantMotherArtId";
	public static final String MIDDLE_NAME = "middleName";
	public static final String AGE = "age";
	public static final String CATEGORY_ID = "categoryId";

}

